### PR TITLE
Feature/ignore forbid set trace

### PR DESCRIPTION
**Pull request by traviswaelbro**
## Include simple support for ignoring hooks flags

This allows disabling and re-enabling of the `forbid-git-conflicts` and `forbid-set-trace` hooks, using comments to turn it off and on, similar to `black`'s `#fmt: off` and `#fmt: on`.

These options can be useful for ignoring "bad content" that is being flagged as a false positive, such as comments, documentation, etc.

```
# forbid-git-conflicts: off
"<<<<<<<"
# forbid-git-conflicts: on
```

```
# forbid-set-trace: off
__import__("ipdb").set_trace()
# forbid-set-trace: on
```

### Notes:

- This release is tagged as `20210929-a`, which is the first tag for this repo.
- The "good stuff" is in the `helpers/` directory. Most of the other files are just copied in to improve code consistency. Reviewing this as separate commits might be helpful.

### CODE REVIEW

**Review by manney — CHANGES_REQUESTED** [review]
I love this.  :heart: 

But you need to set your `.gitignore` to ignore the first four files of this commit.

**Comment by traviswaelbro** [comment]
This isn't like our other repos, so there's nothing to pull them in like normal. 😕

**Comment by manney** [comment]
Problem is that I've updated like 3 of them in my OM PR.  So I guess update them as and when?

**Review by manney — APPROVED** [review]

**Comment by traviswaelbro** [comment]
I guess so. I don't have a great answer for repos like these 😕

**Review by toddythebody — APPROVED** [review]

**Review by samcoydev — APPROVED** [review]

**Pull request merged**
